// Generated by CoffeeScript 1.6.1
(function() {
  var calcPipeHeight, delay, iframe, onPlay, player;

  delay = function(time, callback) {
    return setTimeout(callback, time);
  };

  calcPipeHeight = function(water, animate) {
    var documentHeight, pipeHeight, topOffset;
    if (animate == null) {
      animate = false;
    }
    $('.side-dripper .hose').height(0);
    if (water) {
      $('.side-dripper .water').height(0);
    } else {
      $('.side-dripper .water').height(200);
      $('.side-dripper .water').height(0);
    }
    documentHeight = $(document).height();
    topOffset = $('#our-system').offset().top - parseInt($('#our-system').css('margin-top'), 10) + $('.side-dripper .timer').height() - 70;
    pipeHeight = documentHeight - topOffset;
    $('.side-dripper .hose').height(pipeHeight);
    if (water) {
      if (animate) {
        $('.side-dripper .water').animate({
          height: pipeHeight
        }, 500);
      } else {
        $('.side-dripper .water').height(pipeHeight);
      }
    }
  };

  iframe = $('#vimeo-player')[0];

  player = $f(iframe);

  player.addEvent('ready', function() {
    console.log("Ready");
    player.addEvent('play', onPlay);
  });

  onPlay = function() {
    console.log("Video Play");
    _gaq.push(['_trackEvent', 'Video', 'Play']);
  };

  $(function() {
    $('.inner').localScroll({
      offset: -135
    });
    if (location.hash !== "") {
      $(".inner a." + (location.hash.substring(1))).trigger('click');
    }
    $('.back-to-top').on('click', function() {
      $.scrollTo('0px', 500, {
        axis: 'y'
      });
      return false;
    });
    $('.customer-service').on('click', function() {
      if ($('.phone').hasClass('active')) {
        $('.phone').removeClass('active');
        if (Modernizr.touch) {
          document.removeEventListener('touchstart');
        } else {
          $('body').off('click');
        }
      } else {
        $('.phone').addClass('active');
        if (Modernizr.touch) {
          document.addEventListener('touchstart', function() {
            $('.phone').removeClass('active');
          }, false);
        } else {
          $('body').on('click', function() {
            $('.phone').removeClass('active');
          });
        }
      }
      return false;
    });
    $('nav.buy a, .main-product a, .additional-products a').on('click', function() {
      $('.buy-choices').append('<iframe src="buy-choices.html" />');
      $('.buy-choices').lightbox_me({
        onClose: function() {
          $('.buy-choices').html('');
        }
      });
      return false;
    });
    $('.illustrations').waypoint(function(direction) {
      if (direction === "down") {
        $(this).addClass('animate');
        setTimeout(function() {
          $('.illustrations').removeClass('animate');
        }, 7000);
      }
    }, {
      offset: 300
    });
    $('#our-system').waypoint(function(direction) {
      if (direction === "down") {
        $('nav.inner a').removeClass('active');
        $('nav.inner .our-system').addClass('active');
        return _gaq.push(['_trackEvent', 'Navigation', 'Our System']);
      } else {
        return $('nav.inner a').removeClass('active');
      }
    }, {
      offset: 200
    });
    $('#how-it-works').waypoint(function(direction) {
      if (direction === "down") {
        $('nav.inner a').removeClass('active');
        $('nav.inner .how-it-works').addClass('active');
        return _gaq.push(['_trackEvent', 'Navigation', 'How It Works']);
      } else {
        $('nav.inner a').removeClass('active');
        return $('nav.inner .our-system').addClass('active');
      }
    }, {
      offset: 200
    });
    $('#expand-customize').waypoint(function(direction) {
      if (direction === "down") {
        $('nav.inner a').removeClass('active');
        $('nav.inner .expand-customize').addClass('active');
        return _gaq.push(['_trackEvent', 'Navigation', 'Expand & Customize']);
      } else {
        $('nav.inner a').removeClass('active');
        return $('nav.inner .how-it-works').addClass('active');
      }
    }, {
      offset: 200
    });
    $('.kit-steps').waypoint(function(direction) {
      if (direction === "down") {
        $('.in-the-kit').addClass('animate');
        setTimeout(function() {
          $('.in-the-kit').removeClass('animate');
        }, 5000);
      }
    }, {
      offset: 450
    });
    $('a.house').on('click', function() {
      return false;
    });
    $('.water').waypoint(function(direction) {
      if (direction === "down") {
        $('.water').animate({
          height: 400
        }, 500).css('left', $(this).offset().left).addClass("stuck");
      } else {
        $('.water').removeClass("stuck").css('left', '3px').height($(this).height() - 135).animate({
          height: 0
        }, 500);
      }
    }, {
      offset: 135
    });
    $('.water').waypoint('disable');
    $(window).setBreakpoints({
      breakpoints: [700]
    });
    $(window).bind('enterBreakpoint700', function() {
      $('a.house').unbind('click');
      $('a.house').fancybox();
      $('div.guide .preview').fancybox();
      calcPipeHeight(false);
      $('.illustrations figure').hover(function() {
        $(this).addClass('active');
      }, function() {
        $(this).removeClass('active');
      });
      $('.water').waypoint('enable');
      $(window).resize(function() {
        if ($('.water').hasClass('stuck')) {
          $('.water').css('left', $('.hose').offset().left + 3);
        }
      });
    });
    $(window).bind('exitBreakpoint700', function() {
      $('a.house').unbind('click.fb');
      $('a.house').on('click', function() {
        return false;
      });
      $('.illustrations figure').unbind('hover');
      $('.water').waypoint('disable');
      $('div.guide .preview').unbind('click.fb');
      calcPipeHeight(true);
      $('.water').removeClass('stuck');
    });
  });

  $(window).load(function() {
    if ($(window).width() < 700) {
      calcPipeHeight(true);
    } else {
      calcPipeHeight(false);
    }
  });

}).call(this);
