INSERT INTO `#__rokquickcart` (`id`, `name`, `description`, `price`, `shipping`, `image`, `published`, `checked_out`, `checked_out_time`, `ordering`, `params`) VALUES
(1, 'Sample DVD', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi.  Aenean id quam sed lectus tempor adipiscing.  Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a.  Sed pulvinar quam non massa vulputate congue\r\n', 10.00, 2.00, 'images/rokquickcart/samples/bolt.jpg', 1, 0, '0000-00-00 00:00:00', 2, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(4, 'Sample DVD 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi.  Aenean id quam sed lectus tempor adipiscing.  Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a.  Sed pulvinar quam non massa vulputate congue              ', 59.99, 0.00, 'images/rokquickcart/samples/coraline.jpg', 1, 0, '0000-00-00 00:00:00', 4, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(3, 'Sample DVD 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi. Aenean id quam sed lectus tempor adipiscing. Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a. Sed pulvinar quam non massa vulputate congue', 22.99, 0.00, 'images/rokquickcart/samples/clone-wars.jpg', 1, 0, '0000-00-00 00:00:00', 3, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(6, 'Sample DVD 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi. Aenean id quam sed lectus tempor adipiscing. Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a. Sed pulvinar quam non massa vulputate congue', 8.97, 0.00, 'images/rokquickcart/samples/kung-fu-panda.jpg', 1, 0, '0000-00-00 00:00:00', 6, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(7, 'Sample DVD 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi. Aenean id quam sed lectus tempor adipiscing. Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a. Sed pulvinar quam non massa vulputate congue', 13.49, 1.50, 'images/rokquickcart/samples/run-fat-boy-run.jpg', 1, 0, '0000-00-00 00:00:00', 7, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(8, 'Sample DVD 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi. Aenean id quam sed lectus tempor adipiscing. Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a. Sed pulvinar quam non massa vulputate congue', 12.99, 0.00, 'images/rokquickcart/samples/transporter-3.jpg', 0, 0, '0000-00-00 00:00:00', 8, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(9, 'Sample DVD 8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi. Aenean id quam sed lectus tempor adipiscing. Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a. Sed pulvinar quam non massa vulputate congue', 15.99, 0.00, 'images/rokquickcart/samples/valkyrie.jpg', 0, 0, '0000-00-00 00:00:00', 9, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(10, 'Sample DVD 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi. Aenean id quam sed lectus tempor adipiscing. Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a. Sed pulvinar quam non massa vulputate congue', 8.99, 0.00, 'images/rokquickcart/samples/iron-man.jpg', 1, 0, '0000-00-00 00:00:00', 5, '{\"has_sizes\":\"0\",\"has_colors\":\"0\"}'),
(11, 'Sample Shirt', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.  Donec magna quam, dignissim in pharetra eget, ultrices sit amet nisi.  Aenean id quam sed lectus tempor adipiscing.  Aliquam accumsan hendrerit lectus, quis blandit urna consectetur a.  Sed pulvinar quam non massa vulputate congue', 15.99, 0.00, 'images/rokquickcart/samples/youre_it_tag.jpg', 1, 0, '0000-00-00 00:00:00', 1, '{\"has_sizes\":\"1\",\"sizes\":{\"1\":\"Small\",\"2\":\"Medium\",\"3\":\"Large\"},\"has_colors\":\"1\",\"colors\":{\"1\":\"Black\",\"2\":\"Red\",\"3\":\"Blue\",\"4\":\"Grey\"}}');

UPDATE `#__extensions` set `params`='{\"page_title\":\"Our Products\",\"shelf_item_width\":\"343\",\"shelf_image_width\":\"100\",\"cart_item_width\":\"200\",\"cart_image_width\":\"100\",\"use_rokbox\":\"1\",\"include_css\":\"1\",\"tax\":\"0\",\"tax_rate\":\"0.00\",\"checkout_mode\":\"sandbox\",\"checkout_method\":\"PayPal\",\"paypal_email\":\"\",\"paypal_currency\":\"USD\",\"shipping\":\"0\",\"shipping_type\":\"items\",\"shipping_flat\":\"0.00\",\"shipping_quantity\":\"0.00\",\"shipping_percent\":\"0.00\",\"googlecheckout_merchant_id\":\"\",\"googlecheckout_currency\":\"USD\"}'
WHERE `type`= 'component' and `element`='com_rokquickcart';
